dataset:
  target: src.datasets.motion_clip_dataset.MotionCLIPDataset

  # kwargs:
  dataset_dir: ~/Think-Then-React/data/Inter-X_Dataset
  epoch_scaling: 1
  max_motion_length: 256
  min_motion_length: 32
  motion_representation: intergen_262
  split: 
  tiny_dataset: False